name: Transportation Proxy Pipeline 3 (D-C)
definition: >
  Transportation Proxy Pipeline 3 performs license plate detection on vehicles, enabling automated
  identification and tracking of license plates for transportation analysis and monitoring.
metadata:
  classname: LicensePlateDetectionPipeline
  enabled: true
recording:
  url: "https://videos.pexels.com/video-files/30787543/13168475_1280_720_25fps.mp45"
  filename: license-plate-detection.mp4
